Algoritmo "padaria hotpao"

Var

p,b,pp: real

Inicio

Escreva("Quantidade de pãeszinhos vendidos no dia:")
leia(p)
Escreva("Quantidade de broas vendidas no dia:")
leia(b)

p<-p*0.12
         escreval("Total arrecadado com pães:", p)
b<-b*1.5
        escreval("Total arrecadado com broas", b)
        
pp<-(p+b)/10
            escreva("Quantidade a ser guardada:", pp)
        
        
Fimalgoritmo